#driver pack for WiFi adapters for android kernel by p3h3n9-pr0j3ct
#
obj-y           += rtl8188eus/
obj-y           += rtl8188fu/
obj-y           += rtl8192eu/
obj-y           += rtl8192fu/
obj-y           += rtl8812au/
obj-y	        += rtl8814au/
